"""Alan Watts Library MCP Server.

Exposes the full vectorized corpus to any MCP-compatible LLM client.
Run with: python -m src.mcp_server   (stdio transport)

Tools (7):
  search            — semantic search across 4,293 chunks
  chat              — RAG response in Watts' voice
  list_transcripts  — browse transcripts (filter by series / keyword)
  get_transcript    — full text of a single transcript
  list_series       — all lecture series with counts
  list_topics       — 15 auto-discovered philosophical topics
  get_topic         — topic detail with associated transcripts
"""

import json
import os
import sys

# Ensure repo root is on the path when run as a module
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from fastmcp import FastMCP

from src.db import get_connection
from src.embeddings.provider import embed_text
from src.llm.provider import get_provider
from src.api.routes.chat import ALAN_WATTS_SYSTEM_PROMPT

mcp = FastMCP("Alan Watts Library")


# ── Tool: search ──────────────────────────────────────────────────────────────

@mcp.tool()
def search(query: str, limit: int = 10) -> dict:
    """Semantic search across 238 Alan Watts transcripts (4,293 chunks).

    Returns ranked chunks with similarity scores and source metadata.
    Use this to find specific passages or explore themes.
    """
    if limit < 1 or limit > 50:
        limit = 10

    embedding = embed_text(query)
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT c.id, c.transcript_id, t.title, t.series, c.text,
                       1 - (c.embedding <=> %s::vector) as similarity
                FROM chunks c
                JOIN transcripts t ON t.id = c.transcript_id
                WHERE c.embedding IS NOT NULL
                ORDER BY c.embedding <=> %s::vector
                LIMIT %s
            """, (str(embedding), str(embedding), limit))
            rows = cur.fetchall()
    finally:
        conn.close()

    results = [
        {
            "chunk_id": row[0],
            "transcript_id": row[1],
            "title": row[2],
            "series": row[3],
            "text": row[4],
            "similarity": round(float(row[5]), 4),
        }
        for row in rows
    ]
    return {"query": query, "results": results, "total": len(results)}


# ── Tool: chat ────────────────────────────────────────────────────────────────

@mcp.tool()
def chat(message: str, context_limit: int = 10) -> dict:
    """Ask Alan Watts a question. Returns a RAG response grounded in his actual words.

    The response is generated by an LLM using retrieved transcript excerpts as context,
    with Watts speaking in his own philosophical voice.
    """
    if context_limit < 1 or context_limit > 20:
        context_limit = 10

    embedding = embed_text(message)
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT c.text, t.title, t.series,
                       1 - (c.embedding <=> %s::vector) as similarity
                FROM chunks c
                JOIN transcripts t ON t.id = c.transcript_id
                WHERE c.embedding IS NOT NULL
                ORDER BY c.embedding <=> %s::vector
                LIMIT %s
            """, (str(embedding), str(embedding), context_limit))
            rows = cur.fetchall()
    finally:
        conn.close()

    sources = [
        {"text": row[0], "title": row[1], "series": row[2], "similarity": round(float(row[3]), 4)}
        for row in rows
    ]

    context_parts = []
    for i, src in enumerate(sources, 1):
        label = src["title"]
        if src["series"]:
            label = f"{src['series']} - {src['title']}"
        context_parts.append(f"[Excerpt {i} from \"{label}\"]\n{src['text']}")

    sep = "\n\n---\n\n"
    context_block = sep.join(context_parts)
    user_message = (
        "Based on these excerpts from your lectures and writings, "
        "please respond to the following question or topic.\n\n"
        f"TRANSCRIPT EXCERPTS:\n{context_block}\n\n"
        f"QUESTION/TOPIC: {message}"
    )

    response_text = get_provider().generate(
        system=ALAN_WATTS_SYSTEM_PROMPT,
        user=user_message,
        max_tokens=1500,
    )

    return {
        "response": response_text,
        "sources": [
            {"title": s["title"], "series": s["series"], "similarity": s["similarity"]}
            for s in sources[:5]
        ],
    }


# ── Tool: list_transcripts ────────────────────────────────────────────────────

@mcp.tool()
def list_transcripts(series: str = None, search: str = None, limit: int = 50) -> list:
    """Browse Alan Watts transcripts.

    Args:
        series: Filter by lecture series name (optional).
        search: Keyword search in title or full text (optional).
        limit: Maximum results to return (1-500, default 50).
    """
    if limit < 1 or limit > 500:
        limit = 50

    conn = get_connection()
    try:
        with conn.cursor() as cur:
            conditions = []
            params = []

            if series:
                conditions.append("t.series = %s")
                params.append(series)
            if search:
                conditions.append("(t.title ILIKE %s OR t.full_text ILIKE %s)")
                params.extend([f"%{search}%", f"%{search}%"])

            where = "WHERE " + " AND ".join(conditions) if conditions else ""
            params.append(limit)

            cur.execute(f"""
                SELECT t.id, t.title, t.series, s.name,
                       LENGTH(t.full_text) / 5 as word_count
                FROM transcripts t
                JOIN sources s ON s.id = t.source_id
                {where}
                ORDER BY t.series, t.title
                LIMIT %s
            """, params)
            rows = cur.fetchall()
    finally:
        conn.close()

    return [
        {"id": row[0], "title": row[1], "series": row[2], "source": row[3], "word_count": row[4]}
        for row in rows
    ]


# ── Tool: get_transcript ──────────────────────────────────────────────────────

@mcp.tool()
def get_transcript(transcript_id: int) -> dict:
    """Get the full text of a specific Alan Watts transcript.

    Args:
        transcript_id: Numeric ID from list_transcripts.
    """
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT t.id, t.title, t.series, t.full_text,
                       s.name, t.source_url, t.video_url
                FROM transcripts t
                JOIN sources s ON s.id = t.source_id
                WHERE t.id = %s
            """, (transcript_id,))
            row = cur.fetchone()
    finally:
        conn.close()

    if not row:
        return {"error": f"Transcript {transcript_id} not found"}

    return {
        "id": row[0], "title": row[1], "series": row[2],
        "full_text": row[3], "source": row[4],
        "source_url": row[5], "video_url": row[6],
    }


# ── Tool: list_series ─────────────────────────────────────────────────────────

@mcp.tool()
def list_series() -> list:
    """List all Alan Watts lecture series with transcript counts."""
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT series, COUNT(*) as cnt
                FROM transcripts
                WHERE series IS NOT NULL
                GROUP BY series
                ORDER BY series
            """)
            rows = cur.fetchall()
    finally:
        conn.close()

    return [{"series": row[0], "count": row[1]} for row in rows]


# ── Tool: list_topics ─────────────────────────────────────────────────────────

@mcp.tool()
def list_topics() -> list:
    """List the 15 auto-discovered philosophical topics from the corpus.

    Topics were found via K-Means clustering on 768-dim embeddings.
    Each topic includes keyword tags and chunk/transcript counts.
    """
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT t.id, t.name, t.description,
                       COUNT(tt.transcript_id) as transcript_count
                FROM topics t
                LEFT JOIN transcript_topics tt ON tt.topic_id = t.id
                GROUP BY t.id, t.name, t.description
                ORDER BY (t.description::json->>'chunk_count')::int DESC
            """)
            rows = cur.fetchall()
    finally:
        conn.close()

    results = []
    for row in rows:
        desc = json.loads(row[2]) if row[2] else {}
        results.append({
            "id": row[0],
            "name": row[1],
            "chunk_count": desc.get("chunk_count", 0),
            "transcript_count": int(row[3]),
            "keywords": desc.get("keywords", []),
        })
    return results


# ── Tool: get_topic ───────────────────────────────────────────────────────────

@mcp.tool()
def get_topic(topic_id: int) -> dict:
    """Get topic details with associated transcripts ranked by relevance.

    Args:
        topic_id: Numeric ID from list_topics.
    """
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT id, name, description FROM topics WHERE id = %s", (topic_id,))
            topic_row = cur.fetchone()
            if not topic_row:
                return {"error": f"Topic {topic_id} not found"}

            cur.execute("""
                SELECT t.id, t.title, t.series, s.name,
                       LENGTH(t.full_text) / 5 as word_count,
                       tt.relevance_score
                FROM transcript_topics tt
                JOIN transcripts t ON t.id = tt.transcript_id
                JOIN sources s ON s.id = t.source_id
                WHERE tt.topic_id = %s
                ORDER BY tt.relevance_score DESC
                LIMIT 50
            """, (topic_id,))
            transcript_rows = cur.fetchall()
    finally:
        conn.close()

    desc = json.loads(topic_row[2]) if topic_row[2] else {}

    return {
        "id": topic_row[0],
        "name": topic_row[1],
        "chunk_count": desc.get("chunk_count", 0),
        "transcript_count": desc.get("transcript_count", 0),
        "keywords": desc.get("keywords", []),
        "transcripts": [
            {
                "id": row[0], "title": row[1], "series": row[2],
                "source": row[3], "word_count": row[4],
                "relevance_score": round(float(row[5]), 4),
            }
            for row in transcript_rows
        ],
    }


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    mcp.run()
